//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string passwd { get; set; }
        public string name { get; set; }
        public string rights { get; set; }
        public string group_name { get; set; }
        public string action { get; set; }
        public bool isadmin { get; set; }
    }
}
