//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class board_setup
    {
        public int ID { get; set; }
        public string odd_back { get; set; }
        public string odd_font { get; set; }
        public string even_back { get; set; }
        public string even_font { get; set; }
        public string post_type { get; set; }
        public Nullable<int> pages { get; set; }
        public Nullable<int> board_width { get; set; }
        public bool display_poster { get; set; }
        public Nullable<int> file_size { get; set; }
    }
}
