//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class board
    {
        public int ID { get; set; }
        public string obj { get; set; }
        public string subject { get; set; }
        public string author { get; set; }
        public string homepage_momo { get; set; }
        public string homepage1 { get; set; }
        public string homepage2 { get; set; }
        public string homepage3 { get; set; }
        public string homepage4 { get; set; }
        public string homepage5 { get; set; }
        public string homepage6 { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> postdate { get; set; }
        public Nullable<System.DateTime> posttime { get; set; }
        public Nullable<int> hit { get; set; }
        public string postname { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string post_group { get; set; }
        public Nullable<bool> post_out { get; set; }
        public string post_out_txt { get; set; }
        public string poster_right { get; set; }
        public string file1_momo { get; set; }
        public string file2_momo { get; set; }
        public string file3_momo { get; set; }
        public string file4_momo { get; set; }
        public string file5_momo { get; set; }
        public Nullable<int> created_dept_id { get; set; }
        public string created_user_name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
