//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Subject { get; set; }
        public string theme { get; set; }
        public string cake { get; set; }
        public string service { get; set; }
        public string url { get; set; }
        public string openWindow { get; set; }
        public Nullable<System.DateTime> credate { get; set; }
    }
}
