//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class engcopy
    {
        public int ID { get; set; }
        public string apply_name { get; set; }
        public Nullable<System.DateTime> apply_birth { get; set; }
        public string apply_id { get; set; }
        public string apply_tel { get; set; }
        public string apply_add { get; set; }
        public string apply_email { get; set; }
        public string agent_name { get; set; }
        public Nullable<System.DateTime> agent_birth { get; set; }
        public string agent_id { get; set; }
        public string agent_tel { get; set; }
        public string agent_add { get; set; }
        public string agent_re { get; set; }
        public string company_name { get; set; }
        public string company_add { get; set; }
        public string sarea_1 { get; set; }
        public string sarea_2 { get; set; }
        public string areano_1 { get; set; }
        public string areano_2 { get; set; }
        public string docname_1 { get; set; }
        public string docname_2 { get; set; }
        public string docitem_1 { get; set; }
        public string docitem_2 { get; set; }
        public string docitem_3 { get; set; }
        public string docitem_4 { get; set; }
        public Nullable<int> purpose_1 { get; set; }
        public Nullable<int> purpose_2 { get; set; }
        public Nullable<int> purpose_3 { get; set; }
        public Nullable<int> purpose_4 { get; set; }
        public Nullable<int> purpose_5 { get; set; }
        public string purpose_note { get; set; }
        public Nullable<System.DateTime> wdate { get; set; }
        public string qa_1 { get; set; }
        public string qa_2 { get; set; }
        public string qa_3 { get; set; }
        public string qa_4 { get; set; }
        public string qa_5 { get; set; }
        public string qa_note { get; set; }
    }
}
