//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form
    {
        public int ID { get; set; }
        public string FILETITLE { get; set; }
        public string FILEDESC { get; set; }
        public string FILETYPE { get; set; }
        public string FILECONTENTTYPE { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<int> FILESIZE { get; set; }
        public Nullable<int> HITS { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public string TpcDocNo { get; set; }
    }
}
