//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class landprice
    {
        public int ID { get; set; }
        public string apply_name { get; set; }
        public string apply_id { get; set; }
        public string apply_tel { get; set; }
        public string apply_add { get; set; }
        public string apply_email { get; set; }
        public string purpose { get; set; }
        public string purpose_note { get; set; }
        public string area_1 { get; set; }
        public string area_2 { get; set; }
        public string area_3 { get; set; }
        public string area_4 { get; set; }
        public string area_5 { get; set; }
        public string sarea_1 { get; set; }
        public string sarea_2 { get; set; }
        public string sarea_3 { get; set; }
        public string sarea_4 { get; set; }
        public string sarea_5 { get; set; }
        public string areano_1 { get; set; }
        public string areano_2 { get; set; }
        public string areano_3 { get; set; }
        public string areano_4 { get; set; }
        public string areano_5 { get; set; }
        public string areayear_1 { get; set; }
        public string areayear_2 { get; set; }
        public string areayear_3 { get; set; }
        public string areayear_4 { get; set; }
        public string areayear_5 { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> wdate { get; set; }
        public string qa_1 { get; set; }
        public string qa_2 { get; set; }
        public string qa_3 { get; set; }
        public string qa_4 { get; set; }
        public string qa_5 { get; set; }
    }
}
