//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class landlaw
    {
        public int ID { get; set; }
        public Nullable<int> Classfy { get; set; }
        public string Theme { get; set; }
        public string Cake { get; set; }
        public string Service { get; set; }
        public Nullable<System.DateTime> lDate { get; set; }
        public string Superior { get; set; }
        public string lNumber { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string SubmitName { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Attachfile { get; set; }
        public string Image { get; set; }
        public bool Active { get; set; }
        public string homepage2 { get; set; }
        public string homepage3 { get; set; }
        public string homepage4 { get; set; }
        public string homepage5 { get; set; }
        public string homepage6 { get; set; }
        public string file1_momo { get; set; }
        public string file2_momo { get; set; }
        public string file3_momo { get; set; }
        public string file4_momo { get; set; }
        public string file5_momo { get; set; }
        public Nullable<int> hit { get; set; }
    }
}
