//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lawclass
    {
        public int 識別碼 { get; set; }
        public Nullable<int> classid { get; set; }
        public string classname { get; set; }
        public string creuser { get; set; }
        public string credate { get; set; }
    }
}
