//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class main_menu
    {
        public int id { get; set; }
        public string menuname { get; set; }
        public int menulevel { get; set; }
        public int levelorder { get; set; }
        public int parentid { get; set; }
        public string action { get; set; }
        public string controller { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createuser { get; set; }
    }
}
