//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldPasswordRecored
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public string OldPassword { get; set; }
        public System.DateTime ChangedDate { get; set; }
    
        public virtual admin admin { get; set; }
    }
}
