//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class onlineapp
    {
        public int ID { get; set; }
        public string apply_name { get; set; }
        public Nullable<System.DateTime> apply_birth { get; set; }
        public string apply_id { get; set; }
        public string apply_tel { get; set; }
        public string apply_email { get; set; }
        public string agent_name { get; set; }
        public Nullable<System.DateTime> agent_birth { get; set; }
        public string agent_id { get; set; }
        public string agent_re { get; set; }
        public Nullable<int> app_item_1 { get; set; }
        public Nullable<int> app_item_2 { get; set; }
        public Nullable<int> app_item_3 { get; set; }
        public string year_1 { get; set; }
        public string year_2 { get; set; }
        public string year_3 { get; set; }
        public string docitem_1 { get; set; }
        public string docitem_2 { get; set; }
        public string docitem_3 { get; set; }
        public string no_1 { get; set; }
        public string no_2 { get; set; }
        public string no_3 { get; set; }
        public string copy_1 { get; set; }
        public string copy_2 { get; set; }
        public Nullable<int> purpose_1 { get; set; }
        public Nullable<int> purpose_2 { get; set; }
        public Nullable<int> purpose_3 { get; set; }
        public Nullable<int> purpose_4 { get; set; }
        public Nullable<int> purpose_5 { get; set; }
        public string purpose_note { get; set; }
        public Nullable<System.DateTime> wdate { get; set; }
        public string qa_1 { get; set; }
        public string qa_2 { get; set; }
        public string qa_3 { get; set; }
        public string qa_4 { get; set; }
        public string qa_5 { get; set; }
        public string other_note { get; set; }
        public Nullable<System.DateTime> get_appdate { get; set; }
        public string get_apptime { get; set; }
        public string qa_note { get; set; }
    }
}
