//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal_data
    {
        public int ID { get; set; }
        public System.DateTime ProposalDate { get; set; }
        public string Proposer { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ProposalSubject { get; set; }
        public string ProposalContent { get; set; }
        public string ProposalBenefit { get; set; }
    }
}
