//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa
    {
        public int ID { get; set; }
        public string Theme { get; set; }
        public string Cake { get; set; }
        public string Service { get; set; }
        public Nullable<int> Classfy { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string SubmitName { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> hit { get; set; }
        public Nullable<int> created_dept_id { get; set; }
        public string created_user_name { get; set; }
        public string created_user_phone { get; set; }
    }
}
