//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int type_id { get; set; }
        public string sno { get; set; }
        public string cre_user { get; set; }
        public string typecode { get; set; }
        public string typename { get; set; }
        public Nullable<System.DateTime> cre_date { get; set; }
    }
}
