//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setup_smtp
    {
        public int ID { get; set; }
        public string type { get; set; }
        public string smtp { get; set; }
        public string smtpusername { get; set; }
        public string smtppassword { get; set; }
        public string recipient { get; set; }
        public string recipientname { get; set; }
        public string subject { get; set; }
    }
}
