//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suggest3
    {
        public int answer_id { get; set; }
        public Nullable<short> question_id { get; set; }
        public string writer { get; set; }
        public Nullable<System.DateTime> answer_date { get; set; }
        public string answer { get; set; }
    }
}
