//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suggest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suggest()
        {
            this.suggest2 = new HashSet<suggest2>();
            this.suggest3 = new HashSet<suggest3>();
        }
    
        public int question_id { get; set; }
        public string question_name { get; set; }
        public string owner { get; set; }
        public Nullable<System.DateTime> startday { get; set; }
        public Nullable<System.DateTime> stopday { get; set; }
        public bool is_open { get; set; }
        public string content { get; set; }
        public bool check_ok { get; set; }
        public string who { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suggest2> suggest2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suggest3> suggest3 { get; set; }
    }
}
