//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnlandProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suggest2
    {
        public int id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string question_number { get; set; }
        public string question { get; set; }
        public string type1 { get; set; }
        public string option1 { get; set; }
    
        public virtual suggest suggest { get; set; }
    }
}
